// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package main_test is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockItem is a mock of Item interface.
type MockItem struct {
	ctrl     *gomock.Controller
	recorder *MockItemMockRecorder
}

// MockItemMockRecorder is the mock recorder for MockItem.
type MockItemMockRecorder struct {
	mock *MockItem
}

// NewMockItem creates a new mock instance.
func NewMockItem(ctrl *gomock.Controller) *MockItem {
	mock := &MockItem{ctrl: ctrl}
	mock.recorder = &MockItemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItem) EXPECT() *MockItemMockRecorder {
	return m.recorder
}

// Getlen mocks base method.
func (m *MockItem) Getlen() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getlen")
	ret0, _ := ret[0].(int)
	return ret0
}

// Getlen indicates an expected call of Getlen.
func (mr *MockItemMockRecorder) Getlen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getlen", reflect.TypeOf((*MockItem)(nil).Getlen))
}

// Getname mocks base method.
func (m *MockItem) Getname() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getname")
	ret0, _ := ret[0].(string)
	return ret0
}

// Getname indicates an expected call of Getname.
func (mr *MockItemMockRecorder) Getname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getname", reflect.TypeOf((*MockItem)(nil).Getname))
}
